/*
OneLogin API

OpenAPI Specification for OneLogin

API version: 3.1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package onelogin

import (
	"encoding/json"
)

// checks if the UpdatePrivilege200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdatePrivilege200Response{}

// UpdatePrivilege200Response struct for UpdatePrivilege200Response
type UpdatePrivilege200Response struct {
	// Privilege ID
	Id *string `json:"id,omitempty"`
}

// NewUpdatePrivilege200Response instantiates a new UpdatePrivilege200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdatePrivilege200Response() *UpdatePrivilege200Response {
	this := UpdatePrivilege200Response{}
	return &this
}

// NewUpdatePrivilege200ResponseWithDefaults instantiates a new UpdatePrivilege200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdatePrivilege200ResponseWithDefaults() *UpdatePrivilege200Response {
	this := UpdatePrivilege200Response{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *UpdatePrivilege200Response) GetId() string {
	if o == nil || isNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdatePrivilege200Response) GetIdOk() (*string, bool) {
	if o == nil || isNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *UpdatePrivilege200Response) HasId() bool {
	if o != nil && !isNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *UpdatePrivilege200Response) SetId(v string) {
	o.Id = &v
}

func (o UpdatePrivilege200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdatePrivilege200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	return toSerialize, nil
}

type NullableUpdatePrivilege200Response struct {
	value *UpdatePrivilege200Response
	isSet bool
}

func (v NullableUpdatePrivilege200Response) Get() *UpdatePrivilege200Response {
	return v.value
}

func (v *NullableUpdatePrivilege200Response) Set(val *UpdatePrivilege200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdatePrivilege200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdatePrivilege200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdatePrivilege200Response(val *UpdatePrivilege200Response) *NullableUpdatePrivilege200Response {
	return &NullableUpdatePrivilege200Response{value: val, isSet: true}
}

func (v NullableUpdatePrivilege200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdatePrivilege200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


