/*
OneLogin API

OpenAPI Specification for OneLogin

API version: 3.1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package onelogin

import (
	"encoding/json"
)

// checks if the SamlFactor type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SamlFactor{}

// SamlFactor struct for SamlFactor
type SamlFactor struct {
	// App ID of the app for which you want to generate a SAML token. This is the app ID in OneLogin.
	AppId string `json:"app_id"`
	// Provide the MFA device_id you are submitting for verification. The device_id is supplied by the Generate SAML Assertion API.
	DeviceId string `json:"device_id"`
	// Provide the state_token associated with the MFA device_id you are submitting for verification. The state_token is supplied by the Generate SAML Assertion API.
	StateToken string `json:"state_token"`
	// Provide the OTP value for the MFA factor you are submitting for verification. For some MFA factors; such as OneLogin OTP SMS, which requires the user to request an OTP; the otp_token value is not required, and if not included, returns a 200 OK - Pending result. You’ll make a subsequent Verify Factor API call to provide the otp_token value once it has been provided to the user.
	OtpToken *string `json:"otp_token,omitempty"`
	// When verifying MFA via Protect Push, set this to true to stop additional push notifications being sent to the OneLogin Protect device.
	DoNotNotify *bool `json:"do_not_notify,omitempty"`
}

// NewSamlFactor instantiates a new SamlFactor object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSamlFactor(appId string, deviceId string, stateToken string) *SamlFactor {
	this := SamlFactor{}
	this.AppId = appId
	this.DeviceId = deviceId
	this.StateToken = stateToken
	return &this
}

// NewSamlFactorWithDefaults instantiates a new SamlFactor object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSamlFactorWithDefaults() *SamlFactor {
	this := SamlFactor{}
	return &this
}

// GetAppId returns the AppId field value
func (o *SamlFactor) GetAppId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AppId
}

// GetAppIdOk returns a tuple with the AppId field value
// and a boolean to check if the value has been set.
func (o *SamlFactor) GetAppIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AppId, true
}

// SetAppId sets field value
func (o *SamlFactor) SetAppId(v string) {
	o.AppId = v
}

// GetDeviceId returns the DeviceId field value
func (o *SamlFactor) GetDeviceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DeviceId
}

// GetDeviceIdOk returns a tuple with the DeviceId field value
// and a boolean to check if the value has been set.
func (o *SamlFactor) GetDeviceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DeviceId, true
}

// SetDeviceId sets field value
func (o *SamlFactor) SetDeviceId(v string) {
	o.DeviceId = v
}

// GetStateToken returns the StateToken field value
func (o *SamlFactor) GetStateToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.StateToken
}

// GetStateTokenOk returns a tuple with the StateToken field value
// and a boolean to check if the value has been set.
func (o *SamlFactor) GetStateTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StateToken, true
}

// SetStateToken sets field value
func (o *SamlFactor) SetStateToken(v string) {
	o.StateToken = v
}

// GetOtpToken returns the OtpToken field value if set, zero value otherwise.
func (o *SamlFactor) GetOtpToken() string {
	if o == nil || isNil(o.OtpToken) {
		var ret string
		return ret
	}
	return *o.OtpToken
}

// GetOtpTokenOk returns a tuple with the OtpToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SamlFactor) GetOtpTokenOk() (*string, bool) {
	if o == nil || isNil(o.OtpToken) {
		return nil, false
	}
	return o.OtpToken, true
}

// HasOtpToken returns a boolean if a field has been set.
func (o *SamlFactor) HasOtpToken() bool {
	if o != nil && !isNil(o.OtpToken) {
		return true
	}

	return false
}

// SetOtpToken gets a reference to the given string and assigns it to the OtpToken field.
func (o *SamlFactor) SetOtpToken(v string) {
	o.OtpToken = &v
}

// GetDoNotNotify returns the DoNotNotify field value if set, zero value otherwise.
func (o *SamlFactor) GetDoNotNotify() bool {
	if o == nil || isNil(o.DoNotNotify) {
		var ret bool
		return ret
	}
	return *o.DoNotNotify
}

// GetDoNotNotifyOk returns a tuple with the DoNotNotify field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SamlFactor) GetDoNotNotifyOk() (*bool, bool) {
	if o == nil || isNil(o.DoNotNotify) {
		return nil, false
	}
	return o.DoNotNotify, true
}

// HasDoNotNotify returns a boolean if a field has been set.
func (o *SamlFactor) HasDoNotNotify() bool {
	if o != nil && !isNil(o.DoNotNotify) {
		return true
	}

	return false
}

// SetDoNotNotify gets a reference to the given bool and assigns it to the DoNotNotify field.
func (o *SamlFactor) SetDoNotNotify(v bool) {
	o.DoNotNotify = &v
}

func (o SamlFactor) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SamlFactor) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["app_id"] = o.AppId
	toSerialize["device_id"] = o.DeviceId
	toSerialize["state_token"] = o.StateToken
	if !isNil(o.OtpToken) {
		toSerialize["otp_token"] = o.OtpToken
	}
	if !isNil(o.DoNotNotify) {
		toSerialize["do_not_notify"] = o.DoNotNotify
	}
	return toSerialize, nil
}

type NullableSamlFactor struct {
	value *SamlFactor
	isSet bool
}

func (v NullableSamlFactor) Get() *SamlFactor {
	return v.value
}

func (v *NullableSamlFactor) Set(val *SamlFactor) {
	v.value = val
	v.isSet = true
}

func (v NullableSamlFactor) IsSet() bool {
	return v.isSet
}

func (v *NullableSamlFactor) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSamlFactor(val *SamlFactor) *NullableSamlFactor {
	return &NullableSamlFactor{value: val, isSet: true}
}

func (v NullableSamlFactor) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSamlFactor) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


