/*
OneLogin API

OpenAPI Specification for OneLogin

API version: 3.1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package onelogin

import (
	"encoding/json"
)

// checks if the ClientAppFull type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClientAppFull{}

// ClientAppFull struct for ClientAppFull
type ClientAppFull struct {
	// List of All Scopes assigned to a client app
	Scopes []Scope `json:"scopes,omitempty"`
	// Unique Client App ID
	AppId *int32 `json:"app_id,omitempty"`
	// Name of client app
	Name *string `json:"name,omitempty"`
	ApiAuthId *int32 `json:"api_auth_id,omitempty"`
}

// NewClientAppFull instantiates a new ClientAppFull object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClientAppFull() *ClientAppFull {
	this := ClientAppFull{}
	return &this
}

// NewClientAppFullWithDefaults instantiates a new ClientAppFull object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClientAppFullWithDefaults() *ClientAppFull {
	this := ClientAppFull{}
	return &this
}

// GetScopes returns the Scopes field value if set, zero value otherwise.
func (o *ClientAppFull) GetScopes() []Scope {
	if o == nil || isNil(o.Scopes) {
		var ret []Scope
		return ret
	}
	return o.Scopes
}

// GetScopesOk returns a tuple with the Scopes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientAppFull) GetScopesOk() ([]Scope, bool) {
	if o == nil || isNil(o.Scopes) {
		return nil, false
	}
	return o.Scopes, true
}

// HasScopes returns a boolean if a field has been set.
func (o *ClientAppFull) HasScopes() bool {
	if o != nil && !isNil(o.Scopes) {
		return true
	}

	return false
}

// SetScopes gets a reference to the given []Scope and assigns it to the Scopes field.
func (o *ClientAppFull) SetScopes(v []Scope) {
	o.Scopes = v
}

// GetAppId returns the AppId field value if set, zero value otherwise.
func (o *ClientAppFull) GetAppId() int32 {
	if o == nil || isNil(o.AppId) {
		var ret int32
		return ret
	}
	return *o.AppId
}

// GetAppIdOk returns a tuple with the AppId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientAppFull) GetAppIdOk() (*int32, bool) {
	if o == nil || isNil(o.AppId) {
		return nil, false
	}
	return o.AppId, true
}

// HasAppId returns a boolean if a field has been set.
func (o *ClientAppFull) HasAppId() bool {
	if o != nil && !isNil(o.AppId) {
		return true
	}

	return false
}

// SetAppId gets a reference to the given int32 and assigns it to the AppId field.
func (o *ClientAppFull) SetAppId(v int32) {
	o.AppId = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ClientAppFull) GetName() string {
	if o == nil || isNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientAppFull) GetNameOk() (*string, bool) {
	if o == nil || isNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ClientAppFull) HasName() bool {
	if o != nil && !isNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ClientAppFull) SetName(v string) {
	o.Name = &v
}

// GetApiAuthId returns the ApiAuthId field value if set, zero value otherwise.
func (o *ClientAppFull) GetApiAuthId() int32 {
	if o == nil || isNil(o.ApiAuthId) {
		var ret int32
		return ret
	}
	return *o.ApiAuthId
}

// GetApiAuthIdOk returns a tuple with the ApiAuthId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientAppFull) GetApiAuthIdOk() (*int32, bool) {
	if o == nil || isNil(o.ApiAuthId) {
		return nil, false
	}
	return o.ApiAuthId, true
}

// HasApiAuthId returns a boolean if a field has been set.
func (o *ClientAppFull) HasApiAuthId() bool {
	if o != nil && !isNil(o.ApiAuthId) {
		return true
	}

	return false
}

// SetApiAuthId gets a reference to the given int32 and assigns it to the ApiAuthId field.
func (o *ClientAppFull) SetApiAuthId(v int32) {
	o.ApiAuthId = &v
}

func (o ClientAppFull) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClientAppFull) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Scopes) {
		toSerialize["scopes"] = o.Scopes
	}
	if !isNil(o.AppId) {
		toSerialize["app_id"] = o.AppId
	}
	if !isNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !isNil(o.ApiAuthId) {
		toSerialize["api_auth_id"] = o.ApiAuthId
	}
	return toSerialize, nil
}

type NullableClientAppFull struct {
	value *ClientAppFull
	isSet bool
}

func (v NullableClientAppFull) Get() *ClientAppFull {
	return v.value
}

func (v *NullableClientAppFull) Set(val *ClientAppFull) {
	v.value = val
	v.isSet = true
}

func (v NullableClientAppFull) IsSet() bool {
	return v.isSet
}

func (v *NullableClientAppFull) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClientAppFull(val *ClientAppFull) *NullableClientAppFull {
	return &NullableClientAppFull{value: val, isSet: true}
}

func (v NullableClientAppFull) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClientAppFull) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


