/*
OneLogin API

OpenAPI Specification for OneLogin

API version: 3.1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package onelogin

import (
	"encoding/json"
)

// checks if the GetInviteLinkRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetInviteLinkRequest{}

// GetInviteLinkRequest struct for GetInviteLinkRequest
type GetInviteLinkRequest struct {
	// Set to the user email address to generate an invite link. The value is case sensitive.
	Email *string `json:"email,omitempty"`
}

// NewGetInviteLinkRequest instantiates a new GetInviteLinkRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetInviteLinkRequest() *GetInviteLinkRequest {
	this := GetInviteLinkRequest{}
	return &this
}

// NewGetInviteLinkRequestWithDefaults instantiates a new GetInviteLinkRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetInviteLinkRequestWithDefaults() *GetInviteLinkRequest {
	this := GetInviteLinkRequest{}
	return &this
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *GetInviteLinkRequest) GetEmail() string {
	if o == nil || isNil(o.Email) {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetInviteLinkRequest) GetEmailOk() (*string, bool) {
	if o == nil || isNil(o.Email) {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *GetInviteLinkRequest) HasEmail() bool {
	if o != nil && !isNil(o.Email) {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *GetInviteLinkRequest) SetEmail(v string) {
	o.Email = &v
}

func (o GetInviteLinkRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetInviteLinkRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Email) {
		toSerialize["email"] = o.Email
	}
	return toSerialize, nil
}

type NullableGetInviteLinkRequest struct {
	value *GetInviteLinkRequest
	isSet bool
}

func (v NullableGetInviteLinkRequest) Get() *GetInviteLinkRequest {
	return v.value
}

func (v *NullableGetInviteLinkRequest) Set(val *GetInviteLinkRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableGetInviteLinkRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableGetInviteLinkRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetInviteLinkRequest(val *GetInviteLinkRequest) *NullableGetInviteLinkRequest {
	return &NullableGetInviteLinkRequest{value: val, isSet: true}
}

func (v NullableGetInviteLinkRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetInviteLinkRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


