/*
OneLogin API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3.0.0-alpha.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ErrorStatusErrorsInner struct for ErrorStatusErrorsInner
type ErrorStatusErrorsInner struct {
	Field *string `json:"field,omitempty"`
	Message []string `json:"message,omitempty"`
}

// NewErrorStatusErrorsInner instantiates a new ErrorStatusErrorsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewErrorStatusErrorsInner() *ErrorStatusErrorsInner {
	this := ErrorStatusErrorsInner{}
	return &this
}

// NewErrorStatusErrorsInnerWithDefaults instantiates a new ErrorStatusErrorsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewErrorStatusErrorsInnerWithDefaults() *ErrorStatusErrorsInner {
	this := ErrorStatusErrorsInner{}
	return &this
}

// GetField returns the Field field value if set, zero value otherwise.
func (o *ErrorStatusErrorsInner) GetField() string {
	if o == nil || o.Field == nil {
		var ret string
		return ret
	}
	return *o.Field
}

// GetFieldOk returns a tuple with the Field field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ErrorStatusErrorsInner) GetFieldOk() (*string, bool) {
	if o == nil || o.Field == nil {
		return nil, false
	}
	return o.Field, true
}

// HasField returns a boolean if a field has been set.
func (o *ErrorStatusErrorsInner) HasField() bool {
	if o != nil && o.Field != nil {
		return true
	}

	return false
}

// SetField gets a reference to the given string and assigns it to the Field field.
func (o *ErrorStatusErrorsInner) SetField(v string) {
	o.Field = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *ErrorStatusErrorsInner) GetMessage() []string {
	if o == nil || o.Message == nil {
		var ret []string
		return ret
	}
	return o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ErrorStatusErrorsInner) GetMessageOk() ([]string, bool) {
	if o == nil || o.Message == nil {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *ErrorStatusErrorsInner) HasMessage() bool {
	if o != nil && o.Message != nil {
		return true
	}

	return false
}

// SetMessage gets a reference to the given []string and assigns it to the Message field.
func (o *ErrorStatusErrorsInner) SetMessage(v []string) {
	o.Message = v
}

func (o ErrorStatusErrorsInner) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Field != nil {
		toSerialize["field"] = o.Field
	}
	if o.Message != nil {
		toSerialize["message"] = o.Message
	}
	return json.Marshal(toSerialize)
}

type NullableErrorStatusErrorsInner struct {
	value *ErrorStatusErrorsInner
	isSet bool
}

func (v NullableErrorStatusErrorsInner) Get() *ErrorStatusErrorsInner {
	return v.value
}

func (v *NullableErrorStatusErrorsInner) Set(val *ErrorStatusErrorsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableErrorStatusErrorsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableErrorStatusErrorsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableErrorStatusErrorsInner(val *ErrorStatusErrorsInner) *NullableErrorStatusErrorsInner {
	return &NullableErrorStatusErrorsInner{value: val, isSet: true}
}

func (v NullableErrorStatusErrorsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableErrorStatusErrorsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


