/*
OneLogin API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// CreateRoles201ResponseInner struct for CreateRoles201ResponseInner
type CreateRoles201ResponseInner struct {
	Id *int32 `json:"id,omitempty"`
}

// NewCreateRoles201ResponseInner instantiates a new CreateRoles201ResponseInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateRoles201ResponseInner() *CreateRoles201ResponseInner {
	this := CreateRoles201ResponseInner{}
	return &this
}

// NewCreateRoles201ResponseInnerWithDefaults instantiates a new CreateRoles201ResponseInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateRoles201ResponseInnerWithDefaults() *CreateRoles201ResponseInner {
	this := CreateRoles201ResponseInner{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *CreateRoles201ResponseInner) GetId() int32 {
	if o == nil || o.Id == nil {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateRoles201ResponseInner) GetIdOk() (*int32, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *CreateRoles201ResponseInner) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *CreateRoles201ResponseInner) SetId(v int32) {
	o.Id = &v
}

func (o CreateRoles201ResponseInner) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	return json.Marshal(toSerialize)
}

type NullableCreateRoles201ResponseInner struct {
	value *CreateRoles201ResponseInner
	isSet bool
}

func (v NullableCreateRoles201ResponseInner) Get() *CreateRoles201ResponseInner {
	return v.value
}

func (v *NullableCreateRoles201ResponseInner) Set(val *CreateRoles201ResponseInner) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateRoles201ResponseInner) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateRoles201ResponseInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateRoles201ResponseInner(val *CreateRoles201ResponseInner) *NullableCreateRoles201ResponseInner {
	return &NullableCreateRoles201ResponseInner{value: val, isSet: true}
}

func (v NullableCreateRoles201ResponseInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateRoles201ResponseInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


