/*
OneLogin API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// AddAccessTokenClaimRequest struct for AddAccessTokenClaimRequest
type AddAccessTokenClaimRequest struct {
	Name *string `json:"name,omitempty"`
	UserAttributeMappings *string `json:"user_attribute_mappings,omitempty"`
	UserAttributeMacros *string `json:"user_attribute_macros,omitempty"`
}

// NewAddAccessTokenClaimRequest instantiates a new AddAccessTokenClaimRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddAccessTokenClaimRequest() *AddAccessTokenClaimRequest {
	this := AddAccessTokenClaimRequest{}
	return &this
}

// NewAddAccessTokenClaimRequestWithDefaults instantiates a new AddAccessTokenClaimRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddAccessTokenClaimRequestWithDefaults() *AddAccessTokenClaimRequest {
	this := AddAccessTokenClaimRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *AddAccessTokenClaimRequest) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddAccessTokenClaimRequest) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *AddAccessTokenClaimRequest) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *AddAccessTokenClaimRequest) SetName(v string) {
	o.Name = &v
}

// GetUserAttributeMappings returns the UserAttributeMappings field value if set, zero value otherwise.
func (o *AddAccessTokenClaimRequest) GetUserAttributeMappings() string {
	if o == nil || o.UserAttributeMappings == nil {
		var ret string
		return ret
	}
	return *o.UserAttributeMappings
}

// GetUserAttributeMappingsOk returns a tuple with the UserAttributeMappings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddAccessTokenClaimRequest) GetUserAttributeMappingsOk() (*string, bool) {
	if o == nil || o.UserAttributeMappings == nil {
		return nil, false
	}
	return o.UserAttributeMappings, true
}

// HasUserAttributeMappings returns a boolean if a field has been set.
func (o *AddAccessTokenClaimRequest) HasUserAttributeMappings() bool {
	if o != nil && o.UserAttributeMappings != nil {
		return true
	}

	return false
}

// SetUserAttributeMappings gets a reference to the given string and assigns it to the UserAttributeMappings field.
func (o *AddAccessTokenClaimRequest) SetUserAttributeMappings(v string) {
	o.UserAttributeMappings = &v
}

// GetUserAttributeMacros returns the UserAttributeMacros field value if set, zero value otherwise.
func (o *AddAccessTokenClaimRequest) GetUserAttributeMacros() string {
	if o == nil || o.UserAttributeMacros == nil {
		var ret string
		return ret
	}
	return *o.UserAttributeMacros
}

// GetUserAttributeMacrosOk returns a tuple with the UserAttributeMacros field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddAccessTokenClaimRequest) GetUserAttributeMacrosOk() (*string, bool) {
	if o == nil || o.UserAttributeMacros == nil {
		return nil, false
	}
	return o.UserAttributeMacros, true
}

// HasUserAttributeMacros returns a boolean if a field has been set.
func (o *AddAccessTokenClaimRequest) HasUserAttributeMacros() bool {
	if o != nil && o.UserAttributeMacros != nil {
		return true
	}

	return false
}

// SetUserAttributeMacros gets a reference to the given string and assigns it to the UserAttributeMacros field.
func (o *AddAccessTokenClaimRequest) SetUserAttributeMacros(v string) {
	o.UserAttributeMacros = &v
}

func (o AddAccessTokenClaimRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.UserAttributeMappings != nil {
		toSerialize["user_attribute_mappings"] = o.UserAttributeMappings
	}
	if o.UserAttributeMacros != nil {
		toSerialize["user_attribute_macros"] = o.UserAttributeMacros
	}
	return json.Marshal(toSerialize)
}

type NullableAddAccessTokenClaimRequest struct {
	value *AddAccessTokenClaimRequest
	isSet bool
}

func (v NullableAddAccessTokenClaimRequest) Get() *AddAccessTokenClaimRequest {
	return v.value
}

func (v *NullableAddAccessTokenClaimRequest) Set(val *AddAccessTokenClaimRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAddAccessTokenClaimRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAddAccessTokenClaimRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddAccessTokenClaimRequest(val *AddAccessTokenClaimRequest) *NullableAddAccessTokenClaimRequest {
	return &NullableAddAccessTokenClaimRequest{value: val, isSet: true}
}

func (v NullableAddAccessTokenClaimRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddAccessTokenClaimRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


